// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDihSl5zv0Mz44SIViSJStTjeRshOz-Cw',
    appId: '1:840154289933:web:04f48013e26f787afe4244',
    messagingSenderId: '840154289933',
    projectId: 'ultravetjp-app',
    authDomain: 'ultravetjp-app.firebaseapp.com',
    storageBucket: 'ultravetjp-app.firebasestorage.app',
    measurementId: 'G-EV127710JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUScL7__6P45F3FPMX9QgfL8dxmtALcA',
    appId: '1:840154289933:android:72ec5f87c23b91b9fe4244',
    messagingSenderId: '840154289933',
    projectId: 'ultravetjp-app',
    storageBucket: 'ultravetjp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sbq7KvWhr6hrOp1pyAreyrjZeXpAiG0',
    appId: '1:840154289933:ios:5b18d5f4f89fc468fe4244',
    messagingSenderId: '840154289933',
    projectId: 'ultravetjp-app',
    storageBucket: 'ultravetjp-app.firebasestorage.app',
    iosBundleId: 'com.example.ultravetjpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3sbq7KvWhr6hrOp1pyAreyrjZeXpAiG0',
    appId: '1:840154289933:ios:5b18d5f4f89fc468fe4244',
    messagingSenderId: '840154289933',
    projectId: 'ultravetjp-app',
    storageBucket: 'ultravetjp-app.firebasestorage.app',
    iosBundleId: 'com.example.ultravetjpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDihSl5zv0Mz44SIViSJStTjeRshOz-Cw',
    appId: '1:840154289933:web:89b62fc4e7064a83fe4244',
    messagingSenderId: '840154289933',
    projectId: 'ultravetjp-app',
    authDomain: 'ultravetjp-app.firebaseapp.com',
    storageBucket: 'ultravetjp-app.firebasestorage.app',
    measurementId: 'G-EL14D3W3VS',
  );
}
